print("brutoloon werknemer:")
bl=float(input())
rsz=bl*0.1307
bbl=bl-rsz
bvh=bbl*0.3
nl=bbl-bvh
print("="*42)
print("|",end="")
print(format("LOONFICHE",'^40s'),end="")
print("|")
print("="*42)
print("|",end="")
print(format("Brutoloon",'<28s'),end="")
print("|",end="")
print(f"{bl:>10.2f} ",end="")
print("|")
print("|"+"-"*40+"|")
print("|",end="")
print(format("RSZ bijdrage",'<28s'),end="")
print("|",end="")
print(f"{-rsz:>10.2f} ",end="")
print("|")
print("|"+"-"*40+"|")
print("|",end="")
print(format("Belastbaar inkomen",'<28s'),end="")
print("|",end="")
print(f"{bbl:>10.2f} ",end="")
print("|")
print("|"+"-"*40+"|")
print("|",end="")
print(format("Bedrijfsvoorheffing",'<28s'),end="")
print("|",end="")
print(f"{-bvh:>10.2f} ",end="")
print("|")
print("|"+"-"*40+"|")
print("|",end="")
print(format("Nettoloon",'<28s'),end="")
print("|",end="")
print(f"{nl:>10.2f} ",end="")
print("|")
print("|"+"-"*40+"|")